/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.bankingapplication.Views;

import com.mycompany.AccountManagement.UserAccount;
import com.mycompany.bankingapplication.Controller.Controllable;
import com.mycompany.bankingapplication.Controller.UserInterfaceController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moare
 */
public class LoanApplication extends javax.swing.JPanel implements Controllable {

    /**
     * Creates new form LoanApplication
     */
    public LoanApplication() {
        initComponents();
        incomeTable.getTableHeader().setReorderingAllowed(false);
        slider.setMaximum(0);
        outputTA.setEditable(false);
        errorLBL.setVisible(false);
        refreshBTN.setVisible(false);
    }
    
    private float sum = 0.0f;
    private float maxLoan = 0.0f;
    private int selectedLoan = 0;
    private UserInterfaceController Listener;
    private UserAccount user;

    public void setListener(UserInterfaceController Listener) {
        this.Listener = Listener;
        isUserLoggedIn();
    }

    @Override
    public void setUserDetails() {
        //get current user from controller
        user = Listener.getUser();
        
    }
    
    public void isUserLoggedIn() {
        setUserDetails();
        
        if (user == null) {
            System.out.println("Empty User");
            loanTP.setVisible(false);
            errorLBL.setVisible(true);
            refreshBTN.setVisible(true);
        }else {
            loanTP.setVisible(true);
            errorLBL.setVisible(false);
            refreshBTN.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loanTP = new javax.swing.JTabbedPane();
        incomePane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sourceTF = new javax.swing.JTextField();
        incomeTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        incomeTable = new javax.swing.JTable();
        addBTN = new javax.swing.JButton();
        updateBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        loanApplicationPane = new javax.swing.JPanel();
        loanLBL = new javax.swing.JLabel();
        loanMaxLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        slider = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        selectBTN = new javax.swing.JButton();
        requestBTN = new javax.swing.JButton();
        selectedLoanLBL = new javax.swing.JLabel();
        errorLBL = new javax.swing.JLabel();
        refreshBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Loan Application Form");

        loanTP.setDoubleBuffered(true);

        jLabel2.setText("Source of Income:");

        jLabel3.setText("Monthly Income:");

        incomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Source of Income", "Monthly Income"
            }
        ));
        jScrollPane1.setViewportView(incomeTable);

        addBTN.setBackground(new java.awt.Color(102, 255, 102));
        addBTN.setForeground(new java.awt.Color(0, 0, 0));
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        updateBTN.setBackground(new java.awt.Color(153, 255, 255));
        updateBTN.setForeground(new java.awt.Color(0, 0, 0));
        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });

        deleteBTN.setBackground(new java.awt.Color(255, 51, 51));
        deleteBTN.setForeground(new java.awt.Color(0, 0, 0));
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        jLabel4.setText("<html>Enter all sources of income in the following form before subitting Loan Application to correctly calculate loan range.</html>");

        javax.swing.GroupLayout incomePaneLayout = new javax.swing.GroupLayout(incomePane);
        incomePane.setLayout(incomePaneLayout);
        incomePaneLayout.setHorizontalGroup(
            incomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomePaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(incomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(incomePaneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sourceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(incomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(incomePaneLayout.createSequentialGroup()
                        .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        incomePaneLayout.setVerticalGroup(
            incomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(incomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sourceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(incomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBTN)
                    .addComponent(deleteBTN)
                    .addComponent(addBTN))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        loanTP.addTab("Income Declaration", incomePane);

        loanLBL.setText("Max loan available based on all sources of income and account funds: ");

        loanMaxLBL.setText("€0.00");

        outputTA.setColumns(20);
        outputTA.setRows(5);
        jScrollPane2.setViewportView(outputTA);

        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        selectBTN.setBackground(new java.awt.Color(153, 255, 153));
        selectBTN.setForeground(new java.awt.Color(0, 0, 0));
        selectBTN.setText("<html>Select Desired Loan Amount</html>");
        selectBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBTNActionPerformed(evt);
            }
        });

        requestBTN.setBackground(new java.awt.Color(102, 153, 255));
        requestBTN.setForeground(new java.awt.Color(0, 0, 0));
        requestBTN.setText("<html>Submit Loan Request</html>");
        requestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBTNActionPerformed(evt);
            }
        });

        selectedLoanLBL.setText("€0.00");

        javax.swing.GroupLayout loanApplicationPaneLayout = new javax.swing.GroupLayout(loanApplicationPane);
        loanApplicationPane.setLayout(loanApplicationPaneLayout);
        loanApplicationPaneLayout.setHorizontalGroup(
            loanApplicationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loanApplicationPaneLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(loanApplicationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loanApplicationPaneLayout.createSequentialGroup()
                        .addComponent(loanLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loanMaxLBL))
                    .addGroup(loanApplicationPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(loanApplicationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requestBTN)
                            .addGroup(loanApplicationPaneLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(selectedLoanLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selectBTN))))
                .addGap(87, 87, 87)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loanApplicationPaneLayout.setVerticalGroup(
            loanApplicationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loanApplicationPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(loanApplicationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanLBL)
                    .addComponent(loanMaxLBL))
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loanApplicationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loanApplicationPaneLayout.createSequentialGroup()
                        .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(selectedLoanLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(requestBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        loanTP.addTab("Loan Application", loanApplicationPane);

        errorLBL.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        errorLBL.setForeground(new java.awt.Color(0, 0, 0));
        errorLBL.setText("Please Login or Register an account before attempting to register for a loan");

        refreshBTN.setBackground(new java.awt.Color(153, 255, 153));
        refreshBTN.setForeground(new java.awt.Color(0, 0, 0));
        refreshBTN.setText("Refresh");
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(loanTP, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refreshBTN)
                            .addComponent(errorLBL))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loanTP)
                .addGap(18, 18, 18)
                .addComponent(errorLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshBTN)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        String source = sourceTF.getText().trim();
        float income = -1.0f;
        try {
            income = Float.parseFloat(incomeTF.getText().trim());
            if (income <= 0) {
                throw new Exception("Negative Income Entered");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid positive number for monthly income");
            return;
        }
        sourceTF.setText("");
        incomeTF.setText("");

        DefaultTableModel model = (DefaultTableModel) incomeTable.getModel();
        model.addRow(new Object[]{source, income});
        sum += income;
        maxLoan = sum * 4.0f;
        slider.setMaximum((int) maxLoan);
        loanMaxLBL.setText("€" + ((int) maxLoan));

        outputTA.setText("####################\n"
                + "TOTAL INCOME BASED ON DECLARED INCOME AND CURRENT FUNDS:\n"
                + "€" + sum + "\n"
                + "####################\n");
        isUserLoggedIn();
    }//GEN-LAST:event_addBTNActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        int selectedRow = incomeTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) incomeTable.getModel();
        String source = model.getValueAt(selectedRow, 0).toString();
        float income = (float) model.getValueAt(selectedRow, 1);

        float updatedIncome = -1.0f;

        try {
            updatedIncome = Float.parseFloat(JOptionPane.showInputDialog(this, "Update monthly income for : " + source));

            if (updatedIncome <= 0) {
                throw new Exception("Negative Income Entered");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid positive number for monthly income");
            return;
        }

        model.removeRow(selectedRow);
        model.addRow(new Object[]{source, updatedIncome});
        sum -= income;
        sum += updatedIncome;
        maxLoan = sum * 4.0f;
        slider.setMaximum((int) maxLoan);
        loanMaxLBL.setText("€" + ((int) maxLoan));

        outputTA.setText("####################\n"
                + "TOTAL INCOME BASED ON DECLARED INCOME AND CURRENT FUNDS:\n"
                + "€" + sum + "\n"
                + "####################\n");
    }//GEN-LAST:event_updateBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        int selectedRow = incomeTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) incomeTable.getModel();
        String source = model.getValueAt(selectedRow, 0).toString();
        float income = (float) model.getValueAt(selectedRow, 1);

        int selection = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete:\nSource - " + source + "\nMonthly Income - €" + income);

        if (selection == 0) {
            JOptionPane.showMessageDialog(this, "Source of Income deleted");
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Action Aborted");
        }
        sum -= income;
        maxLoan = sum * 4.0f;
        slider.setMaximum((int) maxLoan);
        loanMaxLBL.setText("€" + ((int) maxLoan));

        outputTA.setText("####################\n"
                + "TOTAL INCOME BASED ON DECLARED INCOME AND CURRENT FUNDS:\n"
                + "€" + sum + "\n"
                + "####################\n");
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        selectedLoanLBL.setText("€" + slider.getValue());
    }//GEN-LAST:event_sliderStateChanged

    private void selectBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBTNActionPerformed
        if (slider.getValue() == 0) {
            JOptionPane.showMessageDialog(this,"Error: no declared income or funds available.");
            return;
        }
        
        selectedLoan = slider.getValue();
        outputTA.setText("####################\n"
                + "TOTAL INCOME BASED ON DECLARED INCOME AND CURRENT FUNDS:\n"
                + "€" + sum + "\n"
                + "--------------------\n"
                + "SELECTED LOAN VALUE:\n"
                + "€" + selectedLoan + " + 4.5% Interest Rate\n"
                + "--------------------\n"
                + "TOTAL LOAN DUE:\n"
                + "€" + ((int) (selectedLoan * 0.045) + selectedLoan) + " due in 12 months\n"
                + "€" + (((int) (selectedLoan * 0.045) + selectedLoan) / 12) + " due each month\n"
                + "####################\n");
    }//GEN-LAST:event_selectBTNActionPerformed

    private void requestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBTNActionPerformed
        if (selectedLoan == 0) {
            JOptionPane.showMessageDialog(this, "Please use the slider to select a loan value and click select button.");
            return;
        }

        JOptionPane.showMessageDialog(this, "Loan Request sent.\n€" + ((int) (selectedLoan * 0.045) + selectedLoan) + " due in 12 months\n€" + (((int) (selectedLoan * 0.045) + selectedLoan) / 12) + " due each month\n");
        Listener.changeCard("HomePage");
    }//GEN-LAST:event_requestBTNActionPerformed

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        isUserLoggedIn();
    }//GEN-LAST:event_refreshBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel errorLBL;
    private javax.swing.JPanel incomePane;
    private javax.swing.JTextField incomeTF;
    private javax.swing.JTable incomeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel loanApplicationPane;
    private javax.swing.JLabel loanLBL;
    private javax.swing.JLabel loanMaxLBL;
    private javax.swing.JTabbedPane loanTP;
    private javax.swing.JTextArea outputTA;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JButton requestBTN;
    private javax.swing.JButton selectBTN;
    private javax.swing.JLabel selectedLoanLBL;
    private javax.swing.JSlider slider;
    private javax.swing.JTextField sourceTF;
    private javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
