/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.bankingapplication.Views;

import com.mycompany.AccountManagement.UserAccount;
import com.mycompany.bankingapplication.Controller.Controllable;
import com.mycompany.bankingapplication.Controller.UserInterfaceController;
import java.awt.Color;

/**
 *
 * @author modus
 */
public class NavMenu extends javax.swing.JPanel implements Controllable {

    /**
     * Creates new form NavMenu
     */
    public NavMenu() {
        initComponents();
    }

    private UserInterfaceController Listener;

    public void setListener(UserInterfaceController Listener) {
        this.Listener = Listener;
    }
    
    public void setUserDetails(){
        //get current user from controller
        UserAccount currentAccount = Listener.getUser();
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountManagementLBL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        transactionsJLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        loanAppLBL = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        homeLBL = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        accountManagementLBL.setText("<html>Account Managment</html>");
        accountManagementLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountManagementLBLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountManagementLBLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountManagementLBLMousePressed(evt);
            }
        });

        transactionsJLabel.setText("Transactions");
        transactionsJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transactionsJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transactionsJLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transactionsJLabelMousePressed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        loanAppLBL.setText("<html>Loan Application</html>");
        loanAppLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanAppLBLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanAppLBLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loanAppLBLMousePressed(evt);
            }
        });

        homeLBL.setText("Home");
        homeLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLBLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLBLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeLBLMousePressed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(transactionsJLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loanAppLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeLBL, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(accountManagementLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(accountManagementLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(transactionsJLabel)
                .addGap(53, 53, 53)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(loanAppLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(homeLBL)
                .addContainerGap(71, Short.MAX_VALUE))
            .addComponent(jSeparator5)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountManagementLBLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountManagementLBLMouseEntered
        accountManagementLBL.setForeground(Color.blue); //change color to blue if mouse detected over label
        
    }//GEN-LAST:event_accountManagementLBLMouseEntered

    private void accountManagementLBLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountManagementLBLMouseExited
        accountManagementLBL.setForeground(Color.black);
    }//GEN-LAST:event_accountManagementLBLMouseExited

    private void accountManagementLBLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountManagementLBLMousePressed
        Listener.changeCard("AccountManagement");
    }//GEN-LAST:event_accountManagementLBLMousePressed

    private void homeLBLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLBLMouseEntered
        homeLBL.setForeground(Color.blue);
    }//GEN-LAST:event_homeLBLMouseEntered

    private void homeLBLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLBLMouseExited
        homeLBL.setForeground(Color.black);
    }//GEN-LAST:event_homeLBLMouseExited

    private void homeLBLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLBLMousePressed
        Listener.changeCard("HomePage");
    }//GEN-LAST:event_homeLBLMousePressed
    //Transactions
    private void transactionsJLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionsJLabelMousePressed
        Listener.changeCard("Transactions");
    }//GEN-LAST:event_transactionsJLabelMousePressed

    private void transactionsJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionsJLabelMouseEntered
        transactionsJLabel.setForeground(Color.blue);
    }//GEN-LAST:event_transactionsJLabelMouseEntered

    private void transactionsJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionsJLabelMouseExited
        transactionsJLabel.setForeground(Color.black);
    }//GEN-LAST:event_transactionsJLabelMouseExited

    private void loanAppLBLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanAppLBLMouseEntered
        loanAppLBL.setForeground(Color.blue);
    }//GEN-LAST:event_loanAppLBLMouseEntered

    private void loanAppLBLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanAppLBLMouseExited
        loanAppLBL.setForeground(Color.black);
    }//GEN-LAST:event_loanAppLBLMouseExited

    private void loanAppLBLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanAppLBLMousePressed
        Listener.changeCard("LoanApplication");
    }//GEN-LAST:event_loanAppLBLMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountManagementLBL;
    private javax.swing.JLabel homeLBL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel loanAppLBL;
    private javax.swing.JLabel transactionsJLabel;
    // End of variables declaration//GEN-END:variables
}
