/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.AccountManagement;

import com.mycompany.bankingapplication.Controller.Controllable;
import com.mycompany.bankingapplication.Controller.UserInterfaceController;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author moise
 */
public class AccountLoginGUI extends javax.swing.JPanel implements Controllable {

    //variable to use AccountsFileInterface
    private AccountsFileInterface accountsFile;

    //variable to use RegistrationLoginInterface
    private RegistrationLoginInterface regisLogi;

    //variable to use UserInterfaceController
    private UserInterfaceController uicListener;

    @Override
    public void setListener(UserInterfaceController uicListener) {
        this.uicListener = uicListener;
    }

    @Override
    public void setUserDetails() {
        //get current user from controller
        UserAccount currentAccount = uicListener.getUser();

        //set user account fields
        if (currentAccount != null) {
            registrationNumTF.setText(currentAccount.getRegistrationNum());
            passwordTF.setText("");

        }
    }

    /**
     * Creates new form AccountLoginGUI
     */
    public AccountLoginGUI() {
        initComponents();
        //initialize a new AccountsFile
        accountsFile = new AccountsFile();
        //load user accounts
        accountsFile.loadFile();
        //initialize a new Authentication with accountsFile and new PasswordHashing(using concrete class here)
        regisLogi = new Authentication(accountsFile, new PasswordHashing());
        //color the panel
        this.setBackground(Color.CYAN);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        registrationNumLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        registrationNumTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();

        titleLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        titleLbl.setText("Account Login");

        loginBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        registrationNumLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        registrationNumLbl.setText("Registration Number");

        passwordLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        passwordLbl.setText("Password");

        registrationNumTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        passwordTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        updateBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updateBtn.setText("Update Account Details");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginBtn)
                .addGap(27, 27, 27)
                .addComponent(updateBtn)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrationNumLbl)
                            .addComponent(passwordLbl))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrationNumTF)
                            .addComponent(passwordTF))))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLbl)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationNumLbl)
                    .addComponent(registrationNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLbl)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(updateBtn))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    //login existing users
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        //try catch in case user enters invalid details
        try {
            //get variables from user
            String registrationNum = registrationNumTF.getText();

            String password = passwordTF.getText();

            //validate and register user if detail are correct and save
            regisLogi.login(registrationNum, password);
            
            //get userDetails
            UserAccount ua=accountsFile.findByRegistrationNum(registrationNum);
            
            //set logged in user in the controller
            uicListener.setUserDetails(ua);

            JOptionPane.showMessageDialog(this, "Login successful.");

            //after login ...
            //uicListener.changeCard();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_loginBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Fill in only the field you to update after selecting the sections you want to  change aside from your login details. ");
        //go to UpdateGUI
        uicListener.changeCard("Update");
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JLabel registrationNumLbl;
    private javax.swing.JTextField registrationNumTF;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
