/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.AccountManagement;

import com.mycompany.bankingapplication.Controller.Controllable;
import com.mycompany.bankingapplication.Controller.UserInterfaceController;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author moise
 */
public class UpdateGUI extends javax.swing.JPanel implements Controllable {
//variable to use AccountsFileInterface

    private AccountsFileInterface accountsFile;

    //variable to use RegistrationLoginInterface
    private RegistrationLoginInterface regisLogi;

    //variable to use AccountUpdateInterface
    private AccountUpdateInterface accountUpdate;

    //new PasswordHashing assigned to hash
    private PasswordHashing hash = new PasswordHashing();

    //variable to use UserInterfaceController
    private UserInterfaceController uicListener;

    //reference UserInterfaceController
    @Override
    public void setListener(UserInterfaceController uicListener) {
        this.uicListener = uicListener;
    }
    //get current logged in user's account details

    @Override
    public void setUserDetails() {
        //get current user from controller
        UserAccount currentAccount = uicListener.getUser();

        //set user account fields
        if (currentAccount != null) {
            fNameTF.setText(currentAccount.getfName());
            lNameTF.setText(currentAccount.getlName());
            emailTF.setText(currentAccount.getEmail());
            registrationNumTF.setText(currentAccount.getRegistrationNum());
            passwordTF.setText("");
            phoneNumberTF.setText(currentAccount.getPhoneNumber());
            addressTF.setText(currentAccount.getAddress());

        }
    }

    /**
     * Creates new form UpdateGUI
     */
    public UpdateGUI() {
        initComponents();
        //initialize a new AccountsFile
        accountsFile = new AccountsFile();
        //load user accounts
        accountsFile.loadFile();
        //initialize a new Authentication with accountsFile and new PasswordHashing(using concrete class here)
        regisLogi = new Authentication(accountsFile, hash);
        //initialize a new AccountUpdate with accountsFile, regisLogi and new PasswordHashing(using concrete class here)
        accountUpdate = new AccountUpdate(accountsFile, regisLogi, new PasswordHashing());
        fNameLbl.setVisible(false);
        fNameTF.setVisible(false);
        lNameLbl.setVisible(false);
        lNameTF.setVisible(false);
        emailLbl.setVisible(false);
        emailTF.setVisible(false);
        passwordLbl.setVisible(true);
        passwordTF.setVisible(true);
        newPasswordLbl.setVisible(false);
        newPasswordTF.setVisible(false);
        phoneNumberLbl.setVisible(false);
        phoneNumberTF.setVisible(false);
        addressLbl.setVisible(false);
        addressTF.setVisible(false);
        //color the panel
        this.setBackground(Color.CYAN);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        fNameTF = new javax.swing.JTextField();
        lNameLbl = new javax.swing.JLabel();
        lNameTF = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        phoneNumberLbl = new javax.swing.JLabel();
        phoneNumberTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JTextField();
        fNameLbl = new javax.swing.JLabel();
        updateProfileRB = new javax.swing.JRadioButton();
        updateContactRB = new javax.swing.JRadioButton();
        updatePasswordRB = new javax.swing.JRadioButton();
        addressLbl = new javax.swing.JLabel();
        registrationNumLbl = new javax.swing.JLabel();
        registrationNumTF = new javax.swing.JTextField();
        newPasswordLbl = new javax.swing.JLabel();
        newPasswordTF = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(110, 25));
        setLayout(null);

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        title.setText("Update Account");
        add(title);
        title.setBounds(273, 21, 109, 18);

        updateBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updateBtn.setText("Update Account");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn);
        updateBtn.setBounds(408, 470, 139, 24);

        fNameTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        fNameTF.setPreferredSize(new java.awt.Dimension(138, 25));
        add(fNameTF);
        fNameTF.setBounds(259, 231, 138, 25);

        lNameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lNameLbl.setText("Last Name");
        add(lNameLbl);
        lNameLbl.setBounds(18, 266, 72, 18);

        lNameTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lNameTF.setPreferredSize(new java.awt.Dimension(138, 25));
        add(lNameTF);
        lNameTF.setBounds(259, 262, 138, 27);

        emailLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        emailLbl.setText("Email");
        add(emailLbl);
        emailLbl.setBounds(18, 310, 38, 18);

        passwordLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        passwordLbl.setText("Password");
        add(passwordLbl);
        passwordLbl.setBounds(20, 119, 67, 18);

        emailTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        emailTF.setPreferredSize(new java.awt.Dimension(138, 25));
        add(emailTF);
        emailTF.setBounds(259, 307, 138, 25);

        phoneNumberLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        phoneNumberLbl.setText("Phone Number");
        add(phoneNumberLbl);
        phoneNumberLbl.setBounds(18, 341, 99, 18);

        phoneNumberTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        phoneNumberTF.setPreferredSize(new java.awt.Dimension(138, 25));
        add(phoneNumberTF);
        phoneNumberTF.setBounds(259, 369, 138, 25);

        addressTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addressTF.setPreferredSize(new java.awt.Dimension(138, 25));
        add(addressTF);
        addressTF.setBounds(259, 338, 138, 25);

        passwordTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        passwordTF.setPreferredSize(new java.awt.Dimension(138, 25));
        add(passwordTF);
        passwordTF.setBounds(259, 114, 138, 25);

        fNameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        fNameLbl.setText("First Name");
        add(fNameLbl);
        fNameLbl.setBounds(17, 234, 73, 18);

        buttonGroup1.add(updateProfileRB);
        updateProfileRB.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updateProfileRB.setText("Update Profile");
        updateProfileRB.setPreferredSize(new java.awt.Dimension(144, 24));
        updateProfileRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileRBActionPerformed(evt);
            }
        });
        add(updateProfileRB);
        updateProfileRB.setBounds(520, 50, 144, 24);

        buttonGroup1.add(updateContactRB);
        updateContactRB.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updateContactRB.setText("Update Contact");
        updateContactRB.setPreferredSize(new java.awt.Dimension(144, 24));
        updateContactRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateContactRBActionPerformed(evt);
            }
        });
        add(updateContactRB);
        updateContactRB.setBounds(520, 80, 144, 24);

        buttonGroup1.add(updatePasswordRB);
        updatePasswordRB.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updatePasswordRB.setText("Update Password");
        updatePasswordRB.setPreferredSize(new java.awt.Dimension(144, 26));
        updatePasswordRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordRBActionPerformed(evt);
            }
        });
        add(updatePasswordRB);
        updatePasswordRB.setBounds(520, 110, 160, 28);

        addressLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addressLbl.setText("Address");
        add(addressLbl);
        addressLbl.setBounds(18, 372, 57, 18);

        registrationNumLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        registrationNumLbl.setText("Registration Number");
        add(registrationNumLbl);
        registrationNumLbl.setBounds(20, 81, 140, 18);

        registrationNumTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        registrationNumTF.setPreferredSize(new java.awt.Dimension(138, 25));
        add(registrationNumTF);
        registrationNumTF.setBounds(259, 81, 138, 25);

        newPasswordLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        newPasswordLbl.setText("New Password");
        add(newPasswordLbl);
        newPasswordLbl.setBounds(17, 186, 100, 18);

        newPasswordTF.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        newPasswordTF.setPreferredSize(new java.awt.Dimension(110, 25));
        add(newPasswordTF);
        newPasswordTF.setBounds(259, 179, 138, 25);
    }// </editor-fold>//GEN-END:initComponents


    private void updateProfileRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileRBActionPerformed
        // TODO add your handling code here:
        fNameLbl.setVisible(true);
        fNameTF.setVisible(true);
        lNameLbl.setVisible(true);
        lNameTF.setVisible(true);
        emailLbl.setVisible(false);
        emailTF.setVisible(false);
        passwordLbl.setVisible(true);
        passwordTF.setVisible(true);
        newPasswordLbl.setVisible(false);
        newPasswordTF.setVisible(false);
        phoneNumberLbl.setVisible(false);
        phoneNumberTF.setVisible(false);
        addressLbl.setVisible(false);
        addressTF.setVisible(false);
    }//GEN-LAST:event_updateProfileRBActionPerformed

    private void updateContactRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateContactRBActionPerformed
        // TODO add your handling code here:
        fNameLbl.setVisible(false);
        fNameTF.setVisible(false);
        lNameLbl.setVisible(false);
        lNameTF.setVisible(false);
        emailLbl.setVisible(false);
        emailTF.setVisible(false);
        passwordLbl.setVisible(true);
        passwordTF.setVisible(true);
        newPasswordLbl.setVisible(false);
        newPasswordTF.setVisible(false);
        phoneNumberLbl.setVisible(true);
        phoneNumberTF.setVisible(true);
        addressLbl.setVisible(true);
        addressTF.setVisible(true);
    }//GEN-LAST:event_updateContactRBActionPerformed

    private void updatePasswordRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePasswordRBActionPerformed
        // TODO add your handling code here:
        fNameLbl.setVisible(false);
        fNameTF.setVisible(false);
        lNameLbl.setVisible(false);
        lNameTF.setVisible(false);
        emailLbl.setVisible(false);
        emailTF.setVisible(false);
        passwordLbl.setVisible(true);
        passwordTF.setVisible(true);
        newPasswordLbl.setVisible(true);
        newPasswordTF.setVisible(true);
        phoneNumberLbl.setVisible(false);
        phoneNumberTF.setVisible(false);
        addressLbl.setVisible(false);
        addressTF.setVisible(false);
    }//GEN-LAST:event_updatePasswordRBActionPerformed
    //update user profile, contact or passowrd
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        String registrationNum = registrationNumTF.getText();
        String password = passwordTF.getText();
        //try catch in case user enters invalid details
        try {
            if (updateProfileRB.isSelected()) {
//                String registrationNum=registrationNumTF.getText();
//                String passowrd=passwordTF.getText();
                String fName = fNameTF.getText();
                String lName = lNameTF.getText();

                //validate update account and save
                accountUpdate.updateProfile(registrationNum, password, fName, lName);

                JOptionPane.showMessageDialog(this, "Profile updated successfully");
                
                //load the file again with updates
                accountsFile.reload();
                
                //find the user's account based on registration number
                UserAccount ua = accountsFile.findByRegistrationNum(registrationNum);
                
                
                //return the updated account details to the user
                JOptionPane.showMessageDialog(this, "Updated Account: \n" + ua.accountDetails());
                
            
                //update controller
                uicListener.setUserDetails(ua);

            }

            if (updateContactRB.isSelected()) {
                String email = emailTF.getText();
                String phoneNumber = phoneNumberTF.getText();
                String address = addressTF.getText();

                accountUpdate.updateContact(registrationNum, password, email, phoneNumber, address);

                //validate update account and save
                JOptionPane.showMessageDialog(this, "Contact updated successfully");

                //find the user's account based on registration number
                UserAccount ua = accountsFile.findByRegistrationNum(registrationNum);

                //return the updated account details to the user
                JOptionPane.showMessageDialog(this, "Updated Account: \n" + ua.accountDetails());
                
                //update controller
                uicListener.setUserDetails(ua);
            }

            if (updatePasswordRB.isSelected()) {
                String newPassword = newPasswordTF.getText();

                //validate update account and save
                regisLogi.updatePassword(registrationNum, password, newPassword);

                JOptionPane.showMessageDialog(this, "Password updated successfully");

                //find the user's account based on registration number
                UserAccount ua = accountsFile.findByRegistrationNum(registrationNum);

                //return the updated account details to the user
                JOptionPane.showMessageDialog(this, "Updated Account: \n" + ua.accountDetails());
                
                //update controller
                uicListener.setUserDetails(ua);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel fNameLbl;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JLabel lNameLbl;
    private javax.swing.JTextField lNameTF;
    private javax.swing.JLabel newPasswordLbl;
    private javax.swing.JTextField newPasswordTF;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JLabel phoneNumberLbl;
    private javax.swing.JTextField phoneNumberTF;
    private javax.swing.JLabel registrationNumLbl;
    private javax.swing.JTextField registrationNumTF;
    private javax.swing.JLabel title;
    private javax.swing.JButton updateBtn;
    private javax.swing.JRadioButton updateContactRB;
    private javax.swing.JRadioButton updatePasswordRB;
    private javax.swing.JRadioButton updateProfileRB;
    // End of variables declaration//GEN-END:variables
}
